# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path, 並讀取 app_train
os.chdir(r'C:\Users\戴嘉萱\Documents\marching learning100day')
dir_data = './w6_data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [3]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [9]:
"""
Your Code Here
"""
sub_train_dummies=pd.get_dummies(sub_train)
print(sub_train_dummies.columns)
print(sub_train.columns)
print(sub_train.shape)
print(sub_train_dummies.shape)
sub_train.head(100)

Index(['WEEKDAY_APPR_PROCESS_START_FRIDAY',
       'WEEKDAY_APPR_PROCESS_START_MONDAY',
       'WEEKDAY_APPR_PROCESS_START_SATURDAY',
       'WEEKDAY_APPR_PROCESS_START_SUNDAY',
       'WEEKDAY_APPR_PROCESS_START_THURSDAY',
       'WEEKDAY_APPR_PROCESS_START_TUESDAY',
       'WEEKDAY_APPR_PROCESS_START_WEDNESDAY'],
      dtype='object')
Index(['WEEKDAY_APPR_PROCESS_START'], dtype='object')
(307511, 1)
(307511, 7)

   WEEKDAY_APPR_PROCESS_START
0                   WEDNESDAY
1                      MONDAY
2                      MONDAY
3                   WEDNESDAY
4                    THURSDAY
5                   WEDNESDAY
6                      SUNDAY
7                      MONDAY
8                   WEDNESDAY
9                    THURSDAY
10                   SATURDAY
11                     FRIDAY
12                     FRIDAY
13                   THURSDAY
14                     MONDAY
15                   SATURDAY
16                   THURSDAY
17                     MONDAY
18                     FRIDAY
19                     MONDAY
20                     FRIDAY
21                     MONDAY
22                   THURSDAY
23                     FRIDAY
24                   THURSDAY
25                   SATURDAY
26                     MONDAY
27                   SATURDAY
28                  WEDNESDAY
29                    TUESDAY
..                        ...
70                     MONDAY
71                     MONDAY
72                     FRIDAY
73                  WEDNESDAY
74                   THURSDAY
75                     FRIDAY
76                   THURSDAY
77                    TUESDAY
78                    TUESDAY
79                   THURSDAY
80                   THURSDAY
81                   THURSDAY
82                   THURSDAY
83                  WEDNESDAY
84                   THURSDAY
85                     FRIDAY
86                  WEDNESDAY
87                     SUNDAY
88                     FRIDAY
89                  WEDNESDAY
90                    TUESDAY
91                  WEDNESDAY
92                  WEDNESDAY
93                     MONDAY
94                     SUNDAY
95                     MONDAY
96                     MONDAY
97                     SUNDAY
98                   THURSDAY
99                    TUESDAY

[100 rows x 1 columns]